"""add uuid_user to professionals

Revision ID: d7e392bc4026
Revises: f96ca91a84f3
Create Date: 2026-06-18 19:57:38.356552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e392bc4026'
down_revision = 'f96ca91a84f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('derecho_fijo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid_user', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(None, ['uuid_user'])
        batch_op.create_foreign_key(None, 'users', ['uuid_user'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uuid_user')

    with op.batch_alter_table('derecho_fijo', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
