"""add uuid_user to professionals

Revision ID: d7e392bc4026
Revises: f96ca91a84f3
Create Date: 2026-06-18 19:57:38.356552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e392bc4026'
down_revision = 'f96ca91a84f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)

    # Check if 'email' column exists in 'derecho_fijo' table
    derecho_fijo_columns = [c['name'] for c in insp.get_columns('derecho_fijo')]
    if 'email' not in derecho_fijo_columns:
        with op.batch_alter_table('derecho_fijo', schema=None) as batch_op:
            batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # Check if 'uuid_user' column exists in 'professionals' table
    professionals_columns = [c['name'] for c in insp.get_columns('professionals')]
    if 'uuid_user' not in professionals_columns:
        with op.batch_alter_table('professionals', schema=None) as batch_op:
            batch_op.add_column(sa.Column('uuid_user', sa.String(length=36), nullable=True))
            batch_op.create_unique_constraint(None, ['uuid_user'])
            batch_op.create_foreign_key(None, 'users', ['uuid_user'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)

    professionals_columns = [c['name'] for c in insp.get_columns('professionals')]
    if 'uuid_user' in professionals_columns:
        with op.batch_alter_table('professionals', schema=None) as batch_op:
            try:
                batch_op.drop_constraint('fk_professionals_uuid_user', type_='foreignkey')
            except Exception:
                pass
            try:
                batch_op.drop_constraint('uq_professionals_uuid_user', type_='unique')
            except Exception:
                pass
            batch_op.drop_column('uuid_user')

    derecho_fijo_columns = [c['name'] for c in insp.get_columns('derecho_fijo')]
    if 'email' in derecho_fijo_columns:
        with op.batch_alter_table('derecho_fijo', schema=None) as batch_op:
            batch_op.drop_column('email')

    # ### end Alembic commands ###
