"""explicacion del cambio

Revision ID: f96ca91a84f3
Revises: 2d3eb93493b3
Create Date: 2026-06-03 21:07:24.161154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f96ca91a84f3'
down_revision = '2d3eb93493b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
