"""explicacion del cambio

Revision ID: f96ca91a84f3
Revises: 2d3eb93493b3
Create Date: 2026-06-03 21:07:24.161154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f96ca91a84f3'
down_revision = '2d3eb93493b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('price_derecho_fijo')
    # op.drop_table('contactos')
    with op.batch_alter_table('derecho_fijo_price', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('value',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('edicts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('subtitle',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.LONGTEXT(),
               nullable=False)
        batch_op.drop_column('tags')

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.String(length=64),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('tuition',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_column('professionalscol')

    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professionalscol', mysql.VARCHAR(length=45), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=False)
        batch_op.alter_column('tuition',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=False)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', mysql.TEXT(), nullable=True))
        batch_op.alter_column('content',
               existing_type=mysql.LONGTEXT(),
               nullable=True)

    with op.batch_alter_table('edicts', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               existing_nullable=False)
        batch_op.alter_column('subtitle',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               existing_nullable=False)

    with op.batch_alter_table('derecho_fijo_price', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('fecha',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)

    op.create_table('contactos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('emaail', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mensaje', mysql.LONGTEXT(), nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('price_derecho_fijo',
    sa.Column('id_table', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', mysql.DATETIME(), nullable=False),
    sa.Column('value', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id_table'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
