"""Constantes de dominio para el módulo de estado de membresía / cuotas."""

MEMBERSHIP_STATUS_UP_TO_DATE = 'UP_TO_DATE'
MEMBERSHIP_STATUS_IN_DEBT = 'IN_DEBT'
MEMBERSHIP_STATUS_EXEMPT_AL_DIA = 'EXEMPT_AL_DIA'
MEMBERSHIP_STATUS_BLOCKED = 'BLOCKED'
MEMBERSHIP_STATUS_AMBIGUOUS = 'AMBIGUOUS'

MEMBERSHIP_STATUSES = {
    MEMBERSHIP_STATUS_UP_TO_DATE,
    MEMBERSHIP_STATUS_IN_DEBT,
    MEMBERSHIP_STATUS_EXEMPT_AL_DIA,
    MEMBERSHIP_STATUS_BLOCKED,
    MEMBERSHIP_STATUS_AMBIGUOUS,
}

STATUSES_CAN_BOOK_MEETING = {
    MEMBERSHIP_STATUS_UP_TO_DATE,
    MEMBERSHIP_STATUS_EXEMPT_AL_DIA,
}

IMPORT_STATUS_PENDING = 'pending'
IMPORT_STATUS_PROCESSING = 'processing'
IMPORT_STATUS_COMPLETED = 'completed'
IMPORT_STATUS_FAILED = 'failed'

SOURCE_TYPE_GOOGLE_SHEETS_CSV = 'google_sheets_csv'
SOURCE_TYPE_FILE_UPLOAD = 'file_upload'

DEFAULT_SHEET_NAME = 'Listado Prof.'
